#/*version: '3.8'
#services:
#  mysql-db:
#    image: 'mysql:latest'
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: transactiondb
#    ports:
#      - '3307:3306'
#    volumes:
#      - /d/mysql-backup:/var/lib/mysql
#
#  application:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-db
#    ports:
#      - '9595:9292'
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/transactiondb'
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password
#volumes:
#  mysql-backup:
